export const PRESET_SESSIONS = [
  {
    id: 'preset-week1-lunge',
    name: 'Sem 1-2 - Cuerda',
    description: 'Trabajo a la cuerda, 28 min',
    preset: true,
    intervals: [
      { name: 'Paso calentamiento', minutes: 5, type: 'paso' },
      { name: 'Trote mano izquierda', minutes: 4, type: 'trote' },
      { name: 'Paso', minutes: 2, type: 'descanso' },
      { name: 'Trote mano derecha', minutes: 4, type: 'trote' },
      { name: 'Paso', minutes: 2, type: 'descanso' },
      { name: 'Galope mano izquierda', minutes: 2, type: 'galope' },
      { name: 'Paso', minutes: 2, type: 'descanso' },
      { name: 'Galope mano derecha', minutes: 2, type: 'galope' },
      { name: 'Paso vuelta a la calma', minutes: 5, type: 'paso' },
    ],
  },
  {
    id: 'preset-week1-mounted',
    name: 'Sem 1-2 - Montado',
    description: 'Trabajo montado basico, 31 min',
    preset: true,
    intervals: [
      { name: 'Paso calentamiento rienda larga', minutes: 5, type: 'paso' },
      { name: 'Trote de trabajo, transiciones', minutes: 5, type: 'trote' },
      { name: 'Cesiones de pierna al paso', minutes: 3, type: 'lateral' },
      { name: 'Trote con espaldas adentro', minutes: 4, type: 'lateral' },
      { name: 'Descanso al paso', minutes: 3, type: 'descanso' },
      { name: 'Galope corto, transiciones', minutes: 3, type: 'galope' },
      { name: 'Trote - galope - trote', minutes: 3, type: 'trote' },
      { name: 'Paso vuelta a la calma', minutes: 5, type: 'paso' },
    ],
  },
  {
    id: 'preset-week3-mounted',
    name: 'Sem 3-4 - Montado',
    description: 'Trabajo montado intermedio, 40 min',
    preset: true,
    intervals: [
      { name: 'Paso calentamiento', minutes: 5, type: 'paso' },
      { name: 'Trote de trabajo', minutes: 5, type: 'trote' },
      { name: 'Espaldas adentro al trote', minutes: 4, type: 'lateral' },
      { name: 'Descanso al paso', minutes: 2, type: 'descanso' },
      { name: 'Galope mano izquierda', minutes: 4, type: 'galope' },
      { name: 'Trocado', minutes: 3, type: 'galope' },
      { name: 'Descanso al paso', minutes: 2, type: 'descanso' },
      { name: 'Galope mano derecha', minutes: 4, type: 'galope' },
      { name: 'Espaldas adentro al galope', minutes: 3, type: 'lateral' },
      { name: 'Trote - transiciones', minutes: 3, type: 'trote' },
      { name: 'Paso vuelta a la calma', minutes: 5, type: 'paso' },
    ],
  },
  {
    id: 'preset-week5-full',
    name: 'Sem 5-6 - Completo',
    description: 'Sesion completa montada, 48 min',
    preset: true,
    intervals: [
      { name: 'Paso calentamiento', minutes: 5, type: 'paso' },
      { name: 'Trote de trabajo, transiciones', minutes: 5, type: 'trote' },
      { name: 'Espaldas adentro trote', minutes: 4, type: 'lateral' },
      { name: 'Cesion de pierna al trote', minutes: 3, type: 'lateral' },
      { name: 'Descanso al paso', minutes: 2, type: 'descanso' },
      { name: 'Galope - transiciones', minutes: 5, type: 'galope' },
      { name: 'Espaldas adentro al galope', minutes: 3, type: 'lateral' },
      { name: 'Trocado', minutes: 3, type: 'galope' },
      { name: 'Descanso al paso', minutes: 2, type: 'descanso' },
      { name: 'Cruzadas y verticales', minutes: 5, type: 'salto' },
      { name: 'Galope recuperacion', minutes: 3, type: 'galope' },
      { name: 'Trote vuelta a la calma', minutes: 3, type: 'trote' },
      { name: 'Paso final', minutes: 5, type: 'paso' },
    ],
  },
  {
    id: 'preset-week7-full',
    name: 'Sem 7+ - Completo',
    description: 'Sesion completa avanzada, 53 min',
    preset: true,
    intervals: [
      { name: 'Paso calentamiento', minutes: 5, type: 'paso' },
      { name: 'Trote de trabajo', minutes: 5, type: 'trote' },
      { name: 'Espaldas adentro trote', minutes: 4, type: 'lateral' },
      { name: 'Cesion y contra-espalda trote', minutes: 4, type: 'lateral' },
      { name: 'Descanso al paso', minutes: 2, type: 'descanso' },
      { name: 'Galope mano izquierda', minutes: 4, type: 'galope' },
      { name: 'Espaldas adentro galope', minutes: 3, type: 'lateral' },
      { name: 'Trocado', minutes: 3, type: 'galope' },
      { name: 'Cambios de pie aislados', minutes: 4, type: 'galope' },
      { name: 'Descanso al paso', minutes: 3, type: 'descanso' },
      { name: 'Cruzadas y verticales', minutes: 8, type: 'salto' },
      { name: 'Galope recuperacion', minutes: 3, type: 'galope' },
      { name: 'Paso vuelta a la calma', minutes: 5, type: 'paso' },
    ],
  },
  {
    id: 'preset-quick-test',
    name: 'Test rapido',
    description: 'Intervalos de 30s para probar, 3 min',
    preset: true,
    intervals: [
      { name: 'Paso calentamiento', minutes: 0.5, type: 'paso' },
      { name: 'Trote de trabajo', minutes: 0.5, type: 'trote' },
      { name: 'Espaldas adentro', minutes: 0.5, type: 'lateral' },
      { name: 'Galope', minutes: 0.5, type: 'galope' },
      { name: 'Cruzadas', minutes: 0.5, type: 'salto' },
      { name: 'Descanso al paso', minutes: 0.5, type: 'descanso' },
    ],
  },
];
